services:
  db:
    image: postgres:16.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: car-rent-db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    external: false
